### ISSUE TITLE
Turn down readthedocs page

### ISSUE THREAD

**Issue by 95-martin-orion** [jbweston/qsim#1]
Hi @jbweston,

I'm one of the owners on the [main qsim repo](https://github.com/quantumlib/qsim), which just launched a website for documentation and tutorials: [quantumai.google/qsim](https://quantumai.google/qsim). In the process of cleaning up old pages, we noticed that the [qsim readthedocs page](https://qsim.readthedocs.io/en/latest/) points to this repo instead of the main one.

In order to avoid confusing new users, could you turn down this readthedocs page?

Thanks,
Orion Martin, on behalf of Google Quantum AI

**Comment by jbweston** [comment]
Hi @95-martin-orion,

The RTD page has been removed; you should be able to register the name now.

Thanks,

Joe
